version: 2.1

commands:
  
executors:
  smallnode:
    docker:
      - image: cimg/node:14.21.3
    resource_class: small

jobs:
  # Precompile all the rust dependencies
  compile:
    executor: smallnode
    steps:
      - run: echo "compile job in rust store"

  test:
    executor: smallnode
    steps:
      - run: echo "test job in rust store"
  win:
    executor: smallnode
    steps:
      - run: echo "win job in rust store"

  droid:
    executor: smallnode
    steps:
      - run: echo "droid job in rust store"
      
  staging:
    executor: smallnode
    steps:
      - run: echo "stage job in rust store"

  prod:
    executor: smallnode
    steps:
      - run: echo "prod job in rust store"

# We only want to trigger this workflow on tags, not pushes to branches.
workflows:
  build:
    jobs:
      - test

      - compile

      - win:
          requires:
            - test
            - compile

      - droid:
          requires:
            - test
            - compile

      - staging:
          requires:
            - win
            - droid

      - prod:
          requires:
            - win
            - droid
